// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnrx-G6lVpdJkBogNO5ojKlVW28lDjuIA',
    appId: '1:210974690555:web:be297faf2c3b6855fd345e',
    messagingSenderId: '210974690555',
    projectId: 'fir-data-ba5e6',
    authDomain: 'fir-data-ba5e6.firebaseapp.com',
    storageBucket: 'fir-data-ba5e6.firebasestorage.app',
    measurementId: 'G-4PYPXDBWFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTx5EOECKLsPHkAKnKLuOtvGGQvrOrq1A',
    appId: '1:210974690555:android:f4922a896ce0d0cffd345e',
    messagingSenderId: '210974690555',
    projectId: 'fir-data-ba5e6',
    storageBucket: 'fir-data-ba5e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX7CCCYutQQkKFEwa-u_zIkRBbqh4eDP8',
    appId: '1:210974690555:ios:79b9f4768cb6becffd345e',
    messagingSenderId: '210974690555',
    projectId: 'fir-data-ba5e6',
    storageBucket: 'fir-data-ba5e6.firebasestorage.app',
    iosClientId: '210974690555-ih5sucb0une4a7js47tqn59q1osd711b.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX7CCCYutQQkKFEwa-u_zIkRBbqh4eDP8',
    appId: '1:210974690555:ios:79b9f4768cb6becffd345e',
    messagingSenderId: '210974690555',
    projectId: 'fir-data-ba5e6',
    storageBucket: 'fir-data-ba5e6.firebasestorage.app',
    iosClientId: '210974690555-ih5sucb0une4a7js47tqn59q1osd711b.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnrx-G6lVpdJkBogNO5ojKlVW28lDjuIA',
    appId: '1:210974690555:web:57a18a4a13f2d8acfd345e',
    messagingSenderId: '210974690555',
    projectId: 'fir-data-ba5e6',
    authDomain: 'fir-data-ba5e6.firebaseapp.com',
    storageBucket: 'fir-data-ba5e6.firebasestorage.app',
    measurementId: 'G-W0VW7G3BVE',
  );
}
